trigger:
  branches:
    include:
      - main

jobs:  
  - job: ScalingGKENodes
    displayName: 'Scale Down GKE Nodes'
    steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            echo $(ServiceAccountKey)
            echo $(ServiceAccountKey) > _key.json
            cat _key.json
        displayName: 'Writing service account json key file'
        
      # - task: Bash@3
      #   inputs:
      #     targetType: 'inline'
      #     script: |
      #       gcloud auth activate-service-account dev-k8s-cluster-admin@boldbi-dev-296107.iam.gserviceaccount.com --key-file=_key.json
      #       current_node_count=$(gcloud container clusters describe development --zone=us-central1-b --project=boldbi-dev-296107 | grep -oP 'currentNodeCount: \K\d+')
      #       echo $current_node_count            
      #       gcloud container clusters update development --zone us-central1-b --project boldbi-dev-296107 --node-pool development-pool --no-enable-autoscaling
      #       sleep 100
      #       yes | gcloud container clusters resize development --zone=us-central1-b --project=boldbi-dev-296107 --node-pool=development-pool --num-nodes=0
      #   displayName: 'Scaling Nodes'

      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            set -e

            # Authenticate
            gcloud auth activate-service-account dev-k8s-cluster-admin@boldbi-dev-296107.iam.gserviceaccount.com --key-file=_key.json

            # Disable autoscaling (necessary to resize manually)
            gcloud container clusters update development \
              --zone=us-central1-b --project=boldbi-dev-296107 \
              --node-pool=development-pool --no-enable-autoscaling

            # Initiate scale-down asynchronously
            echo "Initiating scale-down to zero..."
            op_name=$(yes | gcloud container clusters resize development \
              --zone=us-central1-b --project=boldbi-dev-296107 \
              --node-pool=development-pool --num-nodes=0 --format='value(name)')

            echo "Resize operation started: $op_name"

            # Optional: Wait for it to complete
            gcloud container operations wait $op_name --zone=us-central1-b --project=boldbi-dev-296107

            echo "Scale-down complete."
        displayName: 'Scaling Nodes'

