trigger:
  branches:
    include:
      - main

jobs:  
  - job: ScalingGKENodes
    displayName: 'Scale Down GKE Nodes'
    steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            echo $(ServiceAccountKey)
            echo $(ServiceAccountKey) > _key.json
            cat _key.json
        displayName: 'Writing service account json key file'
        
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            gcloud auth activate-service-account dev-k8s-cluster-admin@boldbi-dev-296107.iam.gserviceaccount.com --key-file=_key.json
            current_node_count=$(gcloud container clusters describe development --zone=us-central1-b --project=boldbi-dev-296107 | grep -oP 'currentNodeCount: \K\d+')
            echo $current_node_count
            
            if [ "$current_node_count" -gt 0 ]; then
              gcloud container clusters update development --zone us-central1-b --project boldbi-dev-296107 --node-pool pool-2 --no-enable-autoscaling
              yes | gcloud container clusters resize development --zone=us-central1-b --project=boldbi-dev-296107 --node-pool=pool-2 --num-nodes=0
            else
              yes | gcloud container clusters resize development --zone=us-central1-b --project=boldbi-dev-296107 --node-pool=pool-2 --num-nodes=1
              gcloud container clusters update development --zone us-central1-b --project boldbi-dev-296107 --node-pool pool-2 --enable-autoscaling --min-nodes 1 --max-nodes 10
            fi
        displayName: 'Scaling Nodes'
