trigger:
  branches:
    include:
      - main

jobs:  
  - job: ScaleDownGKE
    displayName: 'Scale Down GKE Nodes'
    steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            echo $(ServiceAccountKey)
            echo $(ServiceAccountKey) > _key.json'
            cat _key.json
        displayName: 'Writing service account json key file'
        
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            cat _key.json
            gcloud auth activate-service-account boldreports@boldbi-dev-296107.iam.gserviceaccount.com --key-file=_key.json
            gcloud auth list 
        displayName: 'Writing service account json key file'



