trigger:
  branches:
    include:
      - main
      
stages:
  - stage: ScaleDown
    jobs:
      - job: ScaleDownGKE
        displayName: 'Scale Down GKE Nodes'
        steps:
          - script: |
              gcloud container clusters resize "$CLUSTER_NAME" --num-nodes=3 --node-pool="$NODE_POOL_NAME"
            displayName: 'Scale Down GKE Nodes'

  - stage: ScaleUp
    jobs:
      - job: ScaleUpGKE
        displayName: 'Scale Up GKE Nodes'
        steps:
          - script: |
              gcloud container clusters resize "$CLUSTER_NAME" --num-nodes=3 --node-pool="$NODE_POOL_NAME"
            displayName: 'Scale Up GKE Nodes'